#!/usr/bin/env bash


git clone https://github.com/HOL-Theorem-Prover/HOL.git HOL
(cd HOL && git checkout lexgen)

(cd HOL && echo 'val polymllibdir = "/usr/lib/x86_64-linux-gnu";' > tools-poly/poly-includes.ML)
(cd HOL && poly < tools/smart-configure.sml && bin/build)
