#!/usr/bin/env bash

pip install --user setuptools
pip install --user sel4-deps
pip install --user camkes-deps
mkdir camkes
(cd camkes && yes | repo init -u https://github.com/seL4/camkes-manifest.git && repo sync)
