#!/usr/bin/env bash


DIR=$(dirname $0)

git clone https://github.com/loonwerks/formal-methods-workbench.git

(cd formal-methods-workbench/tools/splat \
    && $DIR/HOL/bin/Holmake \
    && cp splat/splat formal-methods-workbench/tools/case/splat.plugin/resources)

(cd formal-methods-workbench/tools \
    && mvn clean install)


  
