#!/usr/bin/env bash

git clone git@github.com:loonwerks/formal-methods-workbench.git


(cd formal-methods-workbench/tools/splat \
    && Holmake \
    && cp splat/splat formal-methods-workbench/tools/case/splat.plugin/resources)

(cd formal-methods-workbench/tools \
    && mvn clean install)


  
