#!/usr/bin/env bash


mkdir -p repos

git clone https://github.com/HOL-Theorem-Prover/HOL.git repos/HOL
(cd repos/HOL && git checkout lexgen)

(cd repos/HOL && echo 'val polymllibdir = "/usr/lib/x86_64-linux-gnu";' > tools-poly/poly-includes.ML)
(cd repos/HOL && poly < tools/smart-configure.sml && bin/build)
