#!/usr/bin/env bash

#installation for ubuntu 18.04

DIR=$(dirname $0)

$DIR/install-pkgs
$DIR/install-hol
$DIR/install-cakeml
$DIR/install-camkes
$DIR/install-fmw
$DIR/install-sireum
$DIR/install-osate
$DIR/export-commands
