#!/usr/bin/env bash

git clone https://github.com/CakeML/cakeml.git
(cd cakeml && git checkout 59886cd0205c1d5d943ef10a26890f79b515b68f)
(wget --quiet https://cakeml.org/cake-x64-64.tar.gz)
(wget --quiet https://cakeml.org/cake-x64-32.tar.gz)
(cd software && tar -xvzf ../cake-x64-64.tar.gz && cd cake-x64-64 && make)
(cd software && tar -xvzf ../cake-x64-32.tar.gz && cd cake-x64-32 && make
